/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


struct Point
{
	int32_t m_x;
	int32_t m_y;
};

int add(int x, int y)
{
	return x + y;
}

double adds(double x, double y)
{
	return x + y;
}

void add_by_pointer(int x, int y, int *result)
{
	*result = x + y;
}

void swapnum(int *i, int *j)
{
  int temp = *i;
  *i = *j;
  *j = temp;
}

int main(void)
{

	int x = 1;
	int y = 2;
	int result = 0;

	add_by_pointer(x, y, &result);

//	int a = 10;
//	int b = 20;
//
//	swapnum(&a, &b);

	/* Loop forever */
	for(;;);
}
