/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//

#define RCC_BASE_ADDR             0x40021000UL
#define RCC_CFGR_OFFSET           0x08UL
#define RCC_CFGR_REG_ADDR         (RCC_BASE_ADDR + RCC_CFGR_OFFSET)

#define GPIOF_BASE_ADDR           0x48001400UL
#define GPIOF_PUPDR_OFFSET        0x0CUL
#define GPIOF_ODR_OFFSET          0x14UL
//

int main(void)
{

  uint32_t *pRCC_CFGR_REG = (uint32_t *)RCC_CFGR_REG_ADDR;

  //* 1. Configure the Clock Source RCC_CFGR Bits27:24 to 0011: HSI16 clock selected
  //! We are writing the value 0x53000000 the in memory address in pRCC_CFGR_REG

  *pRCC_CFGR_REG = 0x53000000; // &= ~(0x3 << 24); // clear 24 and 25 bit position 0x5000 0000

  //* 2. Configure Pin 2/D7/PF13 Bits 27:26 to 01: General purpose output mode

  //* a) Enable the Peripheral Clock (RCC) for GPIOF peripheral connect to AHB2 BUS

  uint32_t *pRCC_AHB2_ENR = (uint32_t *)(RCC_BASE_ADDR + 0x4C);
  *pRCC_AHB2_ENR |= (1 << 0);

  //* b) Configure the mode of the GPIOA pin 5 as Output mode : GPIOx_MODER

  uint32_t *pGPIOF_MODE_REG = (uint32_t *)(GPIOF_BASE_ADDR + 0x00);

  //! 0x2 = 10 then shifted to the left by 26 bits, where 16 is the first bit postion of MODE8
  *pGPIOF_MODE_REG &= ~(0x2 << 26); // Clear
  *pGPIOF_MODE_REG |= (0x2 << 26);  // Set

  //* c) Configure as Pull-Up 01: Pull-up
  uint32_t *pGPIOF_PUPDR_REG = (uint32_t*)(GPIOF_BASE_ADDR + GPIOF_PUPDR_OFFSET);

  *pGPIOF_PUPDR_REG |= (1 << 26);

  //* c) Write 1
  uint32_t *pGPIOF_ODR_REG = (uint32_t*)(GPIOF_BASE_ADDR + GPIOF_ODR_OFFSET);

  *pGPIOF_ODR_REG |= (1 << 13);

  /* Loop forever */
  for (;;)
    ;
}
